from __future__ import annotations

import asyncio
from typing import Any, Protocol


class CoreProtocol(Protocol):
    def get_status(self) -> dict[str, Any]: ...

    def get_detections(self) -> list[dict[str, Any]]: ...

    def get_logs(self) -> list[dict[str, Any]]: ...

    async def initialize(self) -> str: ...

    async def detect_scene(self) -> str: ...

    async def start_salad(self, recipe: dict[str, int], *, dry_run: bool) -> str: ...

    async def request_stop(self) -> None: ...

    async def move_home(self) -> str: ...

    async def cleanup(self) -> None: ...

    def clear_logs(self) -> None: ...

    def subscribe(self) -> asyncio.Queue[dict[str, Any]]: ...

    def unsubscribe(self, queue: asyncio.Queue[dict[str, Any]]) -> None: ...

    async def shutdown(self) -> None: ...
